# Generated by Django 4.1.4 on 2022-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, 'GRAMM'), (1, 'MilliLITR'), (3, 'DONA')]),
        ),
    ]
