# Generated by Django 4.1.4 on 2022-12-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_slug_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=221, unique=True),
        ),
    ]
